
(define (domain or-push-new) 

   (:requirements :strips :typing)
   (:types pos obj)
   (:constants  o1 o2 o3 o4 o5 o6 o7 o8 o9 o10 o11 o12 o13 o14 o15 - obj) 
   (:predicates (adj ?i ?j - pos) (at ?i - pos) (ncleared ?i - pos) (holding ?o - obj) (obj-at ?o - obj ?i - pos)
                (pick-loc ?i - pos))
   (:action move
      :parameters (?i - pos ?j - pos )
      :precondition (and (adj ?i ?j) (at ?i) (ncleared ?j))
      :effect (and (not (at ?i)) (at ?j)))
   (:action pickup
      :parameters (?i - pos )
      :precondition (and (at ?i) (pick-loc ?i))
      :effect (and 
		   (when (obj-at o1 ?i) (and (holding o1) (not (obj-at o1 ?i))))
		   (when (obj-at o2 ?i) (and (holding o2) (not (obj-at o2 ?i))))
		   (when (obj-at o3 ?i) (and (holding o3) (not (obj-at o3 ?i))))
		   (when (obj-at o4 ?i) (and (holding o4) (not (obj-at o4 ?i))))
		   (when (obj-at o5 ?i) (and (holding o5) (not (obj-at o5 ?i))))
		   (when (obj-at o6 ?i) (and (holding o6) (not (obj-at o6 ?i))))
		   (when (obj-at o7 ?i) (and (holding o7) (not (obj-at o7 ?i))))
		   (when (obj-at o8 ?i) (and (holding o8) (not (obj-at o8 ?i))))
		   (when (obj-at o9 ?i) (and (holding o9) (not (obj-at o9 ?i))))
		   (when (obj-at o10 ?i) (and (holding o10) (not (obj-at o10 ?i))))
		   (when (obj-at o11 ?i) (and (holding o11) (not (obj-at o11 ?i))))
		   (when (obj-at o12 ?i) (and (holding o12) (not (obj-at o12 ?i))))
		   (when (obj-at o13 ?i) (and (holding o13) (not (obj-at o13 ?i))))
		   (when (obj-at o14 ?i) (and (holding o14) (not (obj-at o14 ?i))))
		   (when (obj-at o15 ?i) (and (holding o15) (not (obj-at o15 ?i)))))
   )
   (:action push
      :parameters (?i - pos  ?j - pos )
      :precondition (and (adj ?i ?j) (at ?i))
      :effect (and (not (ncleared ?i)) 
                 (when (obj-at o1 ?i) (and (obj-at o1 ?j) (not (obj-at o1 ?i)) (ncleared ?j)))
                 (when (obj-at o2 ?i) (and (obj-at o2 ?j) (not (obj-at o2 ?i)) (ncleared ?j)))
                 (when (obj-at o3 ?i) (and (obj-at o3 ?j) (not (obj-at o3 ?i)) (ncleared ?j)))
                 (when (obj-at o4 ?i) (and (obj-at o4 ?j) (not (obj-at o4 ?i)) (ncleared ?j)))
                 (when (obj-at o5 ?i) (and (obj-at o5 ?j) (not (obj-at o5 ?i)) (ncleared ?j)))
                 (when (obj-at o6 ?i) (and (obj-at o6 ?j) (not (obj-at o6 ?i)) (ncleared ?j)))
                 (when (obj-at o7 ?i) (and (obj-at o7 ?j) (not (obj-at o7 ?i)) (ncleared ?j)))
                 (when (obj-at o8 ?i) (and (obj-at o8 ?j) (not (obj-at o8 ?i)) (ncleared ?j)))
                 (when (obj-at o9 ?i) (and (obj-at o9 ?j) (not (obj-at o9 ?i)) (ncleared ?j)))
                 (when (obj-at o10 ?i) (and (obj-at o10 ?j) (not (obj-at o10 ?i)) (ncleared ?j)))
                 (when (obj-at o11 ?i) (and (obj-at o11 ?j) (not (obj-at o11 ?i)) (ncleared ?j)))
                 (when (obj-at o12 ?i) (and (obj-at o12 ?j) (not (obj-at o12 ?i)) (ncleared ?j)))
                 (when (obj-at o13 ?i) (and (obj-at o13 ?j) (not (obj-at o13 ?i)) (ncleared ?j)))
                 (when (obj-at o14 ?i) (and (obj-at o14 ?j) (not (obj-at o14 ?i)) (ncleared ?j)))
                 (when (obj-at o15 ?i) (and (obj-at o15 ?j) (not (obj-at o15 ?i)) (ncleared ?j))))
   )
)

