(define (problem p)
  (:domain hall-rotate)
  (:init
    (q0) (north)
    (y-agent p1)
    (oneof (x-agent p1) (x-agent p2) (x-agent p3))
    (not-obs---q0)
    (not-obsA--q0)
    (not-obsB--q0)
    (not-obsC--q0)
    (not-obsD--q0)
    (not-obs-W-q0)
    (not-obsAW-q0)
    (not-obsBW-q0)
    (not-obsCW-q0)
    (not-obsDW-q0)
  )
  (:goal (and (x-agent p1) (y-agent p1) (visited-A) (visited-B) (visited-D) (visited-C)))
)
