(define (problem p1)
  (:domain adder)
  (:objects t f t1 t2 t3 x1 y1 r1 z1 r2 z2 - bit)
  (:init  (high t) (low f)
              (low r1) 
	      (low r2) 
              (low z1) (low z2) 
              (low t1) (low t2) (low t3)
              (oneof (low x1) (high x1))
              (oneof (low y1) (high y1))
              (constant x1) 
              (constant y1)
	      (constant r1) 
	      (constant t)
	      (constant f)
	      (in x1) (in y1) (in r1)
	      (out z1) (out r2)
        )
  
  (:goal (and (constant z1)
	      (constant r2) 
	      (constant z2)
	      (low r1)
              (or (low z2) (high r2))
              (or (low r2) (high z2))
              (or (low r2) (high x1) (high y1))
              (or (low r2) (high x1) (high r1))
              (or (low r2) (high y1) (high r1))
              (or (low x1) (low y1) (high r2))
              (or (low x1) (low r1) (high r2))
              (or (low y1) (low r1) (high r2))
              (or (low z1) (low x1) (high y1) (low r1))
              (or (low z1) (low x1) (low y1) (high r1))
              (or (low z1) (high x1) (low y1) (low r1))
              (or (low z1) (high x1) (high y1) (high r1))
              (or (low x1) (low y1) (low r1) (high z1))
              (or (low x1) (high y1) (high r1) (high z1))
              (or (high x1) (low y1) (high r1) (high z1))
              (or (high x1) (high y1) (low r1) (high z1))
        )
  )
)
