
(define (problem gripper-30)
   (:domain gripper)
   
   (:objects rooma roomb1 roomb2 roomc - room
              ball1  ball2  ball3  ball4  ball5  ball6  ball7  ball8  ball9  ball10  ball11  ball12  ball13  ball14  ball15  ball16  ball17  ball18  ball19  ball20  ball21  ball22  ball23  ball24  ball25  ball26  ball27  ball28  ball29  ball30   - ball)    
    (:init (and 
          (at-robby rooma)
          (free left)
          (free right)
          (det roomb1 roomc)
          (det roomc roomb1)

          (det roomb2 roomc)
          (det roomc roomb2)

          (non-det rooma roomb1 roomb2)

          (det roomb1 rooma)
          (det roomb2 rooma)

          (at ball1 rooma) 
          (at ball2 rooma) 
          (at ball3 rooma) 
          (at ball4 rooma) 
          (at ball5 rooma) 
          (at ball6 rooma) 
          (at ball7 rooma) 
          (at ball8 rooma) 
          (at ball9 rooma) 
          (at ball10 rooma) 
          (at ball11 rooma) 
          (at ball12 rooma) 
          (at ball13 rooma) 
          (at ball14 rooma) 
          (at ball15 rooma) 
          (at ball16 rooma) 
          (at ball17 rooma) 
          (at ball18 rooma) 
          (at ball19 rooma) 
          (at ball20 rooma) 
          (at ball21 rooma) 
          (at ball22 rooma) 
          (at ball23 rooma) 
          (at ball24 rooma) 
          (at ball25 rooma) 
          (at ball26 rooma) 
          (at ball27 rooma) 
          (at ball28 rooma) 
          (at ball29 rooma) 
          (at ball30 rooma) 
    )) 
    (:goal (and 
         (at ball1 roomc) 
         (at ball2 roomc) 
         (at ball3 roomc) 
         (at ball4 roomc) 
         (at ball5 roomc) 
         (at ball6 roomc) 
         (at ball7 roomc) 
         (at ball8 roomc) 
         (at ball9 roomc) 
         (at ball10 roomc) 
         (at ball11 roomc) 
         (at ball12 roomc) 
         (at ball13 roomc) 
         (at ball14 roomc) 
         (at ball15 roomc) 
         (at ball16 roomc) 
         (at ball17 roomc) 
         (at ball18 roomc) 
         (at ball19 roomc) 
         (at ball20 roomc) 
         (at ball21 roomc) 
         (at ball22 roomc) 
         (at ball23 roomc) 
         (at ball24 roomc) 
         (at ball25 roomc) 
         (at ball26 roomc) 
         (at ball27 roomc) 
         (at ball28 roomc) 
         (at ball29 roomc) 
         (at ball30 roomc) 
    ))
)
