(define (problem p9)
 (:domain forest)
 (:objects sx1 sx2 
           sy1 sy2 - sub_location
 )
 (:init 
	;;;;;;;;top level grid;;;;;;;
  (oneof  (at x1) (at x2) (at x3) (at x4) (at x5) (at x6) (at x7) (at x8) (at x9))
  (oneof  (at y1) (at y2) (at y3) (at y4) (at y5) (at y6) (at y7) (at y8) (at y9))
  (succ_loc x1 x2)
  (succ_loc x2 x3)
  (succ_loc x3 x4)
  (succ_loc x4 x5)
  (succ_loc x5 x6)
  (succ_loc x6 x7)
  (succ_loc x7 x8)
  (succ_loc x8 x9)
  (succ_loc y1 y2)
  (succ_loc y2 y3)
  (succ_loc y3 y4)
  (succ_loc y4 y5)
  (succ_loc y5 y6)
  (succ_loc y6 y7)
  (succ_loc y7 y8)
  (succ_loc y8 y9)
	;;;;;;;;subproblems;;;;;;;;;;
  (prob_at x1 blocksworld)
	 (s_on c a x1) (s_on_table a x1) (s_on_table b x1)
  (s_clear b x1) (s_clear c x1) (s_empty x1)
  (prob_at x2 blocksworld)
	 (s_on c a x2) (s_on_table a x2) (s_on_table b x2)
  (s_clear b x2) (s_clear c x2) (s_empty x2)
  (prob_at x3 blocksworld)
	 (s_on c a x3) (s_on_table a x3) (s_on_table b x3)
  (s_clear b x3) (s_clear c x3) (s_empty x3)
  (prob_at x4 logistics)
  (s_pkg_at p1 l12 x4) (s_truck_at t1 l12 x4)
  (s_truck_at t2 l21 x4) (s_plane_at a1 l11 x4)
  (prob_at x5 logistics)
  (s_pkg_at p1 l12 x5) (s_truck_at t1 l12 x5)
  (s_truck_at t2 l21 x5) (s_plane_at a1 l11 x5)
  (prob_at x6 grid)
	 (s_at_x sx2 x6)
	 (s_at_y sy2 x6)
	 (s_goal_x sx1 x6)
  (s_goal_y sy1 x6)
  (prob_at x7 grid)
	 (s_at_x sx2 x7)
	 (s_at_y sy2 x7)
	 (s_goal_x sx1 x7)
  (s_goal_y sy1 x7)
  (prob_at x8 grid)
	 (s_at_x sx2 x8)
	 (s_at_y sy2 x8)
	 (s_goal_x sx1 x8)
  (s_goal_y sy1 x8)
  (prob_at x9 blocksworld)
	 (s_on c a x9) (s_on_table a x9) (s_on_table b x9)
  (s_clear b x9) (s_clear c x9) (s_empty x9)
  (prob_at y1 blocksworld)
  (s_on c a y1) (s_on_table a y1) (s_on_table b y1)
  (s_clear b y1) (s_clear c y1) (s_empty y1)
  (prob_at y2 logistics)
  (s_pkg_at p1 l12 y2) (s_truck_at t1 l12 y2)
  (s_truck_at t2 l21 y2) (s_plane_at a1 l11 y2)
  (prob_at y3 logistics)
  (s_pkg_at p1 l12 y3) (s_truck_at t1 l12 y3)
  (s_truck_at t2 l21 y3) (s_plane_at a1 l11 y3)
  (prob_at y4 logistics)
  (s_pkg_at p1 l12 y4) (s_truck_at t1 l12 y4)
  (s_truck_at t2 l21 y4) (s_plane_at a1 l11 y4)
  (prob_at y5 grid)
	 (s_at_x sx2 y5)
	 (s_at_y sy2 y5)
	 (s_goal_x sx1 y5)
	 (s_goal_y sy1 y5)
  (prob_at y6 grid)
	 (s_at_x sx2 y6)
	 (s_at_y sy2 y6)
	 (s_goal_x sx1 y6)
	 (s_goal_y sy1 y6)
  (prob_at y7 blocksworld)
  (s_on c a y7) (s_on_table a y7) (s_on_table b y7)
  (s_clear b y7) (s_clear c y7) (s_empty y7)
  (prob_at y8 blocksworld)
  (s_on c a y8) (s_on_table a y8) (s_on_table b y8)
  (s_clear b y8) (s_clear c y8) (s_empty y8)
  (prob_at y9 blocksworld)
  (s_on c a y9) (s_on_table a y9) (s_on_table b y9)
  (s_clear b y9) (s_clear c y9) (s_empty y9)
	;;;all grid problems
  (s_succ_loc sx1 sx2)
  (s_succ_loc sy1 sy2)

  ;;;;;;logistics sub-problem;;
  (s_city_loc l11 c1) (s_city_loc l12 c1)
  (s_city_loc l21 c2) (s_city_loc l22 c2)
  (s_airport_loc l11) (s_airport_loc l21)
  (neq l11 l12) (neq l11 l21) (neq l11 l22)
  (neq l12 l11) (neq l12 l21) (neq l12 l22)
  (neq l21 l12) (neq l21 l11) (neq l21 l22)
  (neq l22 l12) (neq l22 l21) (neq l22 l11)

 )
 (:goal 
	(and (at x1) (at y1))
 )
)
